-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: c25201a00e6b0514370501050cf2a8538ac12270
    hooks:
    -   id: remove-crlf
-   repo: https://github.com/reyoung/mirrors-yapf.git
    sha: v0.13.2
    hooks:
    - id: yapf
      files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$  # Bazel BUILD files follow Python syntax.
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 7539d8bd1a00a3c1bfd34cdb606d3a6372e83469
    hooks:
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
- repo: local
  hooks:
    -  id: convert-markdown-into-html
       name: convert-markdown-into-html
       description: "Convert README.md into index.html and README.en.md into index.en.html"
       entry: python pre-commit-hooks/convert_markdown_into_html.py
       language: system
       files: \.md$
