language: cpp
cache: ccache
sudo: required
dist: trusty
os:
  - linux
env:
  - JOB=PRE_COMMIT

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
      - go
before_install:
  -  pip install virtualenv pre-commit
install:
  -  GOPATH=/tmp/go go get -u github.com/wangkuiyi/ipynb/markdown-to-ipynb
script:
  - travis/precommit.sh
notifications:
  email:
    on_success: change
    on_failure: always
